---
title: Modeling, Model Comparison,  and the General Linear Model
draft: true
author: William Murrah
date: '2018-01-10'
slug: modeling-GLM
tags: ["ERMA7300", "ERMA7310", "ERMA8320", "ERMA8340"]
---

In this post I present a brief overview of a model comparison approach to the general linear model. 
The goal is to establish a framework to understand basic statistical methods including $t$ tests, analysis of variance, and linear regression. 
This framework and the example data are from [Maxwell, Delaney, and Kelly (2018)](https://designingexperiments.com/).
Follow this link to find information on this textbook and the accompanying website. Both are excellent, but the text is somewhat advanced for those just learning statistical methods.
Here, I attempt to present these concepts simply, but will necessarily gloss over important aspects that you will want to revisit once you have more experience with basic statistical models.

## Models in Science

> *"All models are wrong, but some are useful"* - [George Box](https://en.wikipedia.org/wiki/All_models_are_wrong#cite_note-2)


Scientists are most often interesting in a small number of variables, but recognize that other things may impact the relations between those key variables.
We could try to include all the variable that are related to our key variables, but that lead us down a very slippery slope. 
If we consider reality a very complex closed system, and acknowledge that all things within a closed system influence all other things in that system -- either directly or indirectly -- we  eventually  realize, **to perfectly model anything, we have to model everything**. 
I doubt this will ever be possible, strictly speaking.
While some may debate this hypothetical, I think we can all agree that it is certainly not currently practical.

This lead to the quote that started this section. 
What Box meant was that because all comprehensible models leave out many important factors that influence our key variables, they are not perfectly accurate.
But, the included variable may be enough to give us insight into how things might work.
To understand reality we need to simplify it enough to make it comprehensible.

A model can be thought of as a map explaining the relations between our key variables.
For example, suppose we work at a university and notice that a disproportionatly large percentage of new students are having problems with entry level math courses. We want to do something about that, but where do we start? 
There are many research questions that we can pose to help understand this issue.
For example, we could which student characteristics predict problems with math. 
Or, could evaluate different study habits, or the amount of time spent studying during these courses.
Eventually, we may get to a point where we understand what is going on enough to develop an intervention for entering freshman aimed at improving their performance in these courses. 
In future posts I may explore these various questions, their designs, and the methods we can use to attempt to answer them.
In this post, I want to use some of them to illustrate basics concepts related to theoretical and statistical models.
are interested in how study habits affect math achievement among college students. 
We have two constructs that we are interested in: study habits, and math achievement.

## The General Linear Model 

$$
\text{Dependent Variable} = \mbox{sum of modeled factors} + \text{sum of unmodeled factors} 
$$

## Restricted Model

$$
Y_i = \mu + \varepsilon_i \tag{1}
$$

## Full Model

$$
Y_i = \beta_0X_i + \varepsilon_i \tag{2}
$$


[Designing Experiments website]